pipelines:
  - name: check
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: comment-added
          branch: master
          comment_filter: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck migrations\s*$
        - event: comment-added
          branch: master
          comment_filter: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$
        - event: patchset-created
          branch: master
        - event: change-restored
          branch: master
    start:
      smtp:
        to: "joshua.hesketh+zuul@gmail.com"
    success:
      smtp:
        to: "joshua.hesketh+zuul@gmail.com"
      gerrit:
        verified: 1
#      mysql:
#        verified: 1
    failure:
      smtp:
        to: "joshua.hesketh+zuul@gmail.com, turbo-hipster@lists.rcbops.com"
#      mysql:
#        verified: -1
      gerrit:
        verified: -1
    success-message: "Database migration testing successful."
    failure-message: "Database migration testing failed either due to migrations unable to be applied correctly or taking too long."
    footer-message: "To recheck, leave 'recheck migrations' as a comment. More information: https://wiki.openstack.org/wiki/Nova/Turbo-Hipster"

  - name: experimental
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          comment_filter: (?i)^\s*check experimental migrations\s*$
    start:
      smtp:
        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
    success:
      smtp:
        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
    failure:
      smtp:
        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
    success-message: "Experimental database migration testing successful."
    failure-message: "Experimental database migration testing failed either due to migrations unable to be applied correctly or taking too long."
    footer-message: "To recheck, leave 'recheck migrations' as a comment. More information: https://wiki.openstack.org/wiki/Nova/Turbo-Hipster"

  - name: silent
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          branch: master
          comment_filter: (?i)^\s*this silent thing should never trigger\s*$
    start:
      smtp:
        to: "michael.still@rackspace.com"
    success:
      smtp:
        to: "michael.still@rackspace.com"
    failure:
      smtp:
        to: "michael.still@rackspace.com"
    success-message: "Silent test passed"
    failure-message: "Silent test failed"
    footer-message: "To recheck, leave 'recheck migrations' as a comment. More information: https://wiki.openstack.org/wiki/Nova/Turbo-Hipster"

jobs:
  - name: ^real-db-upgrade_.*$
    failure-message: Database updates did not apply well to a real set of data...
  - name: ^.*user_001$
    voting: true

projects:
  - name: openstack/nova
    check:
      - real-db-upgrade_nova_mysql_devstack_131007:th-mysql
      - real-db-upgrade_nova_mysql_user_001:th-mysql
      - real-db-upgrade_nova_percona_devstack_131007:th-percona
      - real-db-upgrade_nova_percona_user_001:th-percona
      - real-db-upgrade_nova_mysql_user_002:th-mysql
      - real-db-upgrade_nova_percona_user_002:th-percona
    experimental:
      # This would probably want to be limited to just the 1 job you want to debug when actually doing the debugging
      - real-db-upgrade_nova_mysql_devstack_131007:th-mysql-debug
      - real-db-upgrade_nova_mysql_user_001:th-mysql-debug
      - real-db-upgrade_nova_percona_devstack_131007:th-percona-debug
      - real-db-upgrade_nova_percona_user_001:th-percona-debug
      - real-db-upgrade_nova_mysql_user_002:th-mysql-debug
      - real-db-upgrade_nova_percona_user_002:th-percona-debug
    silent:
      - real-db-upgrade_nova_mysql_devstack_131007:th-mysql
      - real-db-upgrade_nova_mysql_user_001:th-mysql
      - real-db-upgrade_nova_percona_devstack_131007:th-percona
      - real-db-upgrade_nova_percona_user_001:th-percona
      - real-db-upgrade_nova_mysql_user_002:th-mysql
      - real-db-upgrade_nova_percona_user_002:th-percona
